name: Publish New Release

on:
  workflow_dispatch:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            file: /Users/runner/work/microfetch/microfetch/build/native/nativeCompile/microfetch
          - os: ubuntu-latest
            file: /home/runner/work/microfetch/microfetch/build/native/nativeCompile/microfetch
          - os: windows-latest
            file: D:\a\microfetch\microfetch\build\native\nativeCompile\microfetch.exe
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref_name }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
      - name: build for ${{ matrix.os }} os
        run: ./gradlew nativeCompile
      - name: upload binaries
        uses: actions/upload-artifact@v4.0.0
        with:
          name: microfetch-${{ matrix.os }}
          path: ${{ matrix.file }}
